allowlist:
  - justice.gouv.fr
  - gouv.fr
  - finances.gouv.fr
  - malwarebytes.com
  - nessus.org
  - mitre.org
  - redhat.com
  - talosintelligence.com
  - alienvault.com
  - adobe.com
  - youtube.com
  - linkedin.com
  - twitter.com
  - google.fr
  - w3.org
  - microsoft.com
