workers:
  - module: extractor
    class: Extractor
    cache: 1h
    timeout: 1m
    replicas: 5
  - module: olevba
    class: OleVBA
    cache: 1h
    timeout: 1m
    replicas: 2
  - module: preview
    class: Preview
    cache: 1h
    timeout: 1m
    replicas: 5
