name: Python application - API Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    name: Python ${{ matrix.python-version }} sample

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}

    - name: Install with poetry
      run: |
        python -m pip install --upgrade pip poetry
        poetry install
        echo PANDORA_HOME=`pwd` > .env

    - name: Install redis
      run: |
        pushd ..
        git clone https://github.com/redis/redis.git
        pushd redis
        git checkout 6.2
        make
        popd
        popd

    - name: Run API tests
      run: |
        poetry run start
        sleep 10

        # NOTE: Enable when repo is made public.
        # git clone https://github.com/pandora-analysis/pypandora.git
        # pushd pypandora
        # poetry install
        # poetry run pytest tests/test_web.py
        # popd

        poetry run stop

    - name: Test update script
      run: |
        poetry run update --yes
        sleep 30
        poetry run stop
